# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

dist: xenial
os: linux
cache: packages

apt_packages:
  - libmpfr-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
